---
version: '3.7'
services:
  metabase-relayd:
    build:
      context: .
      args:
        ROOT_IMAGE: perl:5.32.1-slim-bullseye
        IMAGE_VERSION: 0.0.5
    image: alceu/metabase-relayd:0.0.5
    ports:
      - "9090:8080"
    volumes:
      - "$HOME/.metabase:/home/runner/.metabase"
    container_name: metabase-relayd
    environment:
      TZ: UTC
